### ISSUE TITLE
Weird SASS_LIBSASS_PATH issue.

### ISSUE THREAD

**Issue by sambws** [sass/sassc#100]
I'm running Ubuntu 14.10 (pretty new to it), and I'm trying to build SassC. When I try to run ```sudo make```, it tells me that SASS_LIBSASS_PATH isn't defined. After doing an echo, the variable's value seems to be the correct path, directing straight into the root folder of libsass.
```
sam@sam-AY747AA-ABA-p6310y:/usr/local/lib/sassc$ echo $SASS_LIBSASS_PATH
/usr/local/lib/libsass/
sam@sam-AY747AA-ABA-p6310y:/usr/local/lib/sassc$ sudo make
Makefile:131: *** SASS_LIBSASS_PATH must be defined.  Stop.
```
If I could get some help for this, that would be great.

**Comment by mgreter** [comment]
Sudo probably resets the env.
```
sudo echo $SASS_LIBSASS_PATH
```

**Comment by akhleung** [comment]
`sudo -E` will preserve the environment, I believe.

**Comment by sambws** [comment]
@akhleung @mgreter Thanks for the pointers! I was able to make it work using the ```env``` command. Still gotta get used to Unix commands.
