### ISSUE TITLE
Keep /* */ comments when 

### ISSUE THREAD

**Issue by anik786** [sass/sassc#101]
Is there a way to keep /* */ comments when compiling in sassc, when type is compressed, like you do in sass 

I need it because I'm developing a Wordpress theme and they require some comments at the start!

Thanks!

**Comment by xzyfer** [comment]
Ruby Sass does not keep `/* */` comments in compressed mode.

**Comment by anik786** [comment]
Can you please add this as a feature as it sometimes needed such as the circumstance I named above.

**Comment by xzyfer** [comment]
This is not the job of Sass. I recommend against using compressed mode. If you want more control of the output look into using a post processor like PostCSS.
