### ISSUE TITLE
@debug variable in @at-root context gives error

### ISSUE THREAD

**Issue by FrontEndStudio** [sass/sassc#103]
I was trying out some @at-root functionality in sassc 3.2.0-beta.2. Came across the following error:

error message:

<pre>
sassc debug.scss 
Error: non-terminal statement or declaration must end with ';'
        on line 7 of debug.scss
>>         @debug-map {
   ---------------^
</pre>

sass code:

<pre>
$map: (
    'key': 'value',
);

@mixin debug-map($map) {
    @at-root {
        @debug-map {
            __toString__: inspect($map);
            __length__: length($map);
            __keys__: map-keys($map);
            __properties__ {
                @each $key, $value in $map {
                    #{$key}: inspect($value);
                }
            }
        }
    }
}

.debug {
  @include debug-map($map);
}

</pre>

tested on:

sassc -v 
sassc: 3.2.0-beta.2
libsass: 3.2.0-beta.2-21-g3681
sass2scss: 1.0.3

**Comment by xzyfer** [comment]
Thanks for the report @FrontEndStudio. It appears the issue is not related to `@at-root` but in fact die to the parse reading `@debug-map` as `@debug`. As a work around for the time being rename `@debug-map` to something does not start with `@debug`.

**Comment by xzyfer** [comment]
Move this to Libsass - https://github.com/sass/libsass/issues/976
