### ISSUE TITLE
How do you actually build this?

### ISSUE THREAD

**Issue by swervo** [sass/sassc#110]
It would be really helpful if there was some guidance on how to actually build this.
I'm reasonably competent with the command line but it isn't immediately obvious how to do this.

**Comment by xzyfer** [comment]
I believe this information is, unintuitive, in the Libsass wiki

https://github.com/sass/libsass/wiki/Building-Libsass

**Comment by swervo** [comment]
Yes, it is unintuitive. I have built libsass.

What I'm trying to do is to intall sassC. Which is why I posted in this repo.

**Comment by xzyfer** [comment]
Once you set up the environment following those instructions it should just
be a matter of running `make`.

**Comment by swervo** [comment]
So, just to be clear I have followed the instructions on:

https://github.com/sass/libsass/wiki/Building-on-Mac-OS-X

I have libsass installed.

Now, how do I actually use it?

I've read that you can use it with sassC which is why I'm here in this repo and not in the libsass repo.

But how exactly do you use sassC?

**Comment by xzyfer** [comment]
Running make in this repo will produce `bin/sassc` binary. You can execute
commands with sassc the same way you would sass i.e. `./bin/sassc --versuon`

**Comment by swervo** [comment]
@xzyfer I really appreciate your help with this. But I'm not getting it. I have installed libsass and in my:

/usr/local/lib

directory I have:

libltdl.7.dylib	libltdl.a	libltdl.dylib	libsass.0.dylib	libsass.a	libsass.dylib	pkgconfig

But I'm at a loss as to how to use this. If I run 'make' in this directory I get:

make: *** No targets specified and no makefile found.  Stop.

I think there is something very basic missing from my understanding of how this is supposed to work.
Is there something else I'm supposed to do? What are you supposed to do with sassC?

**Comment by swervo** [comment]
OK. I have it now. Misunderstanding.

I was thinking that you had to *install* libsass first but actually here are the steps:

1) Clone the libsass repo
2) Edit your .bash_profile to include:

```
export SASS_LIBSASS_PATH=/Users/you/path/libsass
```

3) Clone the sassC repo
4) cd into the sassC repo
5) Type 'make'
6) Job done!

**Comment by xzyfer** [comment]
Sorry this was so difficult @swervo. You want to create a pull requested adding the installation instructions to the README that'd be awesome! Otherwise feel free to close this issue.

**Comment by swervo** [comment]
PR created. Thanks for your help with this.
