### ISSUE TITLE
Error message is always: "File to read not found or unreadable"

### ISSUE THREAD

**Issue by SRGOM** [sass/sassc#112]
No matter what syntax error I make, I get the above error. The ruby version precisely tells me what's wrong. Is that intended or am I missing something?

**Comment by xzyfer** [comment]
Unable to reproduce this. What is the exact command your running?

**Comment by SRGOM** [comment]
I may have spoken too soon. sassc works fine, but for some reason has issues when I run using sbt-sass (after renaming the binary to sass). Nothing this project should have to worry about.
