### ISSUE TITLE
Command line params, different behaviour from ruby version

### ISSUE THREAD

**Issue by SRGOM** [sass/sassc#114]
sassc is not a drop in replacement for ruby-sass because of its behaviour being different from ruby-sass when it comes to source and destination files.

$sass-ruby inputFile.scss:outputFile.css # Works
$sassc inputFile.scss:outputFile.css # File not readable

**Comment by xzyfer** [comment]
SassC doesn't promise to be a drop in replacement for Ruby Sass. If someone
wants this bad enough we're open to pull requests. However for the time
being we have no plans to match Ruby Sass' CLI.
