### ISSUE TITLE
brew installed sassc reports incorrect version

### ISSUE THREAD

**Issue by drewwells** [sass/sassc#118]
```
% brew info sassc
sassc: stable 3.2.4 (bottled), HEAD
Wrapper around libsass that helps to create command-line apps
https://github.com/sass/sassc
/usr/local/Cellar/sassc/3.1.0 (5 files, 40K)
  Poured from bottle
/usr/local/Cellar/sassc/3.2.4 (5 files, 40K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sassc.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, pkg-config ✔
Required: libsass ✔

% sassc -v
sassc: 3.2.1
libsass: 3.2.5
sass2scss: 1.0.3
```

**Comment by xzyfer** [comment]
I believe the brew install simple checks out the git repo and runs `make`. 

Is it possible that you have the `SASS_*` env we use which is resulting in brew compiling against your local developer checkouts of Libsass/Sass?

**Comment by drewwells** [comment]
I don't think so, this is the only SASS in my env. It could be that the formula is setting one.

This is the only one I could find
```
% env | grep SASS
SASS_LIBSASS_PATH=/path/to/libsass
```

**Comment by mgreter** [comment]
Closing as it is now documented how to set the version if bulidling from tar sources:
https://github.com/sass/sassc/blob/master/docs/building/unix-instructions.md
