### ISSUE TITLE
sassc.exe crashes when using compass mixin border-radius

### ISSUE THREAD

**Issue by janjonas** [sass/sassc#130]
When using the compass mixin "border-radius", sassc.exe crashes and is not able to generate a css file. You can reproduce the problem by putting the compass files from here https://github.com/Compass/compass/tree/stable/core/stylesheets/compass into a folder "lib" and try to compile the following minimal scss file:
```
@import "compass/css3/border-radius";
class {
 @include border-radius(3px);
}
```
with the command:
```
sassc.exe -I lib style.scss style.css
```

I've prepared a zip file containing the compass files and the test scss file: https://dl.dropboxusercontent.com/u/6813071/borderradius.zip
Hope this helps...

Would be great if this problem could be resolved.

**Comment by janjonas** [comment]
I've simplified the scss file that crashes sassc so that no external compass includes are needed. I'm not an SASS expert so maybe one could simplify the example code even more.

```
$compass-extensions: compass-extensions() !default;
$supported-browsers: browsers() !default;
$graceful-usage-threshold: 0.1 !default;

$default-capability-options: (
);

@function prefixes-for-capability($capability, $threshold, $capability-options: $default-capability-options) {
  $result: ();
  @each $prefix in browser-prefixes($supported-browsers) {
    $result: map-merge($result,
                      ($prefix: use-prefix($prefix, $capability, $threshold, $capability-options)));
  }
  @return $result;
}
@mixin with-each-prefix($capability, $threshold, $capability-options: $default-capability-options) {
  @each $prefix, $should-use-prefix in prefixes-for-capability($capability, $threshold, $capability-options) {
  }
}
@function use-prefix($prefix, $capability, $threshold, $capability-options: $default-capability-options) {
  $usage: prefix-usage($prefix, $capability, $capability-options);
  @if $usage > $threshold {
    @return $usage;
  }
  @return false;
}

$border-radius-threshold: $graceful-usage-threshold !default;
$default-border-radius: 5px !default;
@mixin border-radius($radius: $default-border-radius, $vertical-radius: false) {
  @include with-each-prefix(border-radius, $border-radius-threshold) {
  }
}

fooClass {
 @include border-radius(3px);
}
```

Btw: I used the method described here https://github.com/sass/libsass/wiki/Building-on-Windows#building-via-visual-studio-community-2013 to build a sassc.exe.

```
> sassc.exe -v
sassc: 3.2.5-11-g3565
libsass: 3.2.5-155-g295b
sass2scss: 1.0.3
```

**Comment by xzyfer** [comment]
The supplied code sample does not compile with Ruby Sass. Please produce a valid code sample that compiles with Ruby Sass via sassmeister.com

**Comment by janjonas** [comment]
But shouldn't sassc.exe repoort a syntax error in that case instead of just crashing?

**Comment by xzyfer** [comment]
Thanks @janjonas I've looked into this further and narrowed the issue down to two separate issues https://github.com/sass/libsass/issues/1451 and https://github.com/sass/libsass/issues/1452. 

I'm closing this in favour of those.
