### ISSUE TITLE
Request: Add 'install' target to Makefile

### ISSUE THREAD

**Issue by davexunit** [sass/sassc#136]
AFAICT, there is only one file to install: `bin/sassc`.  So, an `install` target could be added to the Makefile that simply installs the `sassc` binary to `$(PREFIX)/bin/sassc`.  The `$PREFIX` variable allows the user to pick where to install e.g. `/usr`, `/usr/local`, somewhere else.

**Comment by mgreter** [comment]
Closing as this should be available by now!
