### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by xzyfer** [sass/sassc#139]
Looks like recent LibSass changes have broken SassC.

https://travis-ci.org/sass/sassc/builds/76286098

This needs to be resolved before we can ship 3.3.

**Comment by am11** [comment]
It breaks on testing the libsass_version API call.
Not sure if this is related, but one difference I noticed is; TravisCI was cloning all branches up until last week, and now they are only pulling the master branch: https://www.diffnow.com/?report=ign1l, line 72. (left passing build and right one is failing the same hash).

**Comment by am11** [comment]
I have narrowed it down to https://github.com/sass/libsass/commit/39e26e97a63de16a04f20d5614af23b396e84c4e.

With previous commit https://github.com/sass/libsass/commit/3b4f46257589cf39d1e2edb02f46d731e3c5cba5, it builds.

Tested it with:

```diff
diff --git a/.travis.yml b/.travis.yml
index 6fd5b9d..382d7bd 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,8 +14,7 @@ env:
 before_install:
   - gem install sass
   - git clone https://github.com/sass/libsass.git
-  - cd libsass && git submodule init && git submodule update && cd ..
+  - cd libsass && git checkout 3b4f46257589cf39d1e2edb02f46d731e3c5cba5
+  - git submodule init && git submodule update && cd ..
   - export SASS_LIBSASS_PATH=$TRAVIS_BUILD_DIR/libsass
```

Then:

```diff
diff --git a/.travis.yml b/.travis.yml
index 6fd5b9d..382d7bd 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,8 +14,7 @@ env:
 before_install:
   - gem install sass
   - git clone https://github.com/sass/libsass.git
-  - cd libsass && git submodule init && git submodule update && cd ..
+  - cd libsass && git checkout 39e26e97a63de16a04f20d5614af23b396e84c4e
+  - git submodule init && git submodule update && cd ..
   - export SASS_LIBSASS_PATH=$TRAVIS_BUILD_DIR/libsass
```

**Comment by saper** [comment]
Why is sassc a separate project? It seems to cause more trouble that it's worth...

**Comment by xzyfer** [comment]
For the same reason perl-libsass, sassc-rails and node-sass. They're
distinctly different projects that use libsass. IMHO it makes sense.

**Comment by saper** [comment]
But:

- it's a circular dependency (you need to have sassc to run tests)

- the build system is tangled together (passing things like `SASS_SPEC_PATH` and `SASS_SASSC_PATH` around. For example, sassc script does prepare or use `SASS_SPEC_PATH` just passes it over to libsass makefiles, etc. etc.

**Comment by xzyfer** [comment]
@saper we should do this and document it clearly.
