### ISSUE TITLE
getting error on installation

### ISSUE THREAD

**Issue by techhysahil** [sass/sassc#151]
i am getting below error...pls help me with this one.
![screen shot 2015-10-26 at 3 34 23 pm](https://cloud.githubusercontent.com/assets/7847056/10726209/4f904c10-7bf7-11e5-84ef-5182d7ec1f75.png)

**Comment by saper** [comment]
This error is unrelated to sassc. You operating system is running too many processes and it blocks.

**Comment by techhysahil** [comment]
okkey... i solve that one. but now i am getting this. I think thr is something wrong with Env var that i set.
![screen shot 2015-10-26 at 8 32 01 pm](https://cloud.githubusercontent.com/assets/7847056/10732561/a7791a82-7c20-11e5-8e55-b47609bc18a2.png)

Any suggestion.
![screen shot 2015-10-26 at 8 30 13 pm](https://cloud.githubusercontent.com/assets/7847056/10732494/6415913a-7c20-11e5-834a-de8673209eaf.png)

**Comment by mgreter** [comment]
Looks like your using funny quotes (`“` vs `"`)?

**Comment by techhysahil** [comment]
i thought it will take path as string...sorry my bad. btw thanks fr helping me out.
