### ISSUE TITLE
Not able to install sassc

### ISSUE THREAD

**Issue by techhysahil** [sass/sassc#152]
I have followed all the steps mentioned at https://github.com/sass/sassc/blob/master/docs/building/unix-instructions.md. but still unable to install it. Steps that i followed with snapshot.
1.  I create a folder name "styleresearch" at location "/Users/sahil/styleresearch".
2. I clone libsass repo using git clone https://github.com/sass/libsass.git.
3. Then i set the env var in bash profile as shown below.
   ![screen shot 2015-10-27 at 2 02 19 pm](https://cloud.githubusercontent.com/assets/7847056/10752933/694d9114-7cb3-11e5-931c-ed44a2cd6d14.png)
4. Even i check it using echo $SASS_LIBSASS_PATH.
   ![screen shot 2015-10-27 at 2 03 42 pm](https://cloud.githubusercontent.com/assets/7847056/10752957/91854dde-7cb3-11e5-8ec4-387418d440d8.png)
5. After this i cloned sassc repo using git clone https://github.com/sass/sassc.git.
6. After this moved into sassc folder using cd ./sassc.
7. finally run "make"......result as shown below...
   ![screen shot 2015-10-27 at 2 07 11 pm](https://cloud.githubusercontent.com/assets/7847056/10753037/3afa3f8c-7cb4-11e5-9c39-78135a75041e.png)
   ![screen shot 2015-10-27 at 2 07 41 pm](https://cloud.githubusercontent.com/assets/7847056/10753038/3afbad36-7cb4-11e5-8e66-958d085edb5a.png)
   ![screen shot 2015-10-27 at 2 07 50 pm](https://cloud.githubusercontent.com/assets/7847056/10753036/3af81e6e-7cb4-11e5-893d-60a736dc1d48.png)
8. Finally trying sassc........result command not found......
   ![screen shot 2015-10-27 at 2 08 22 pm](https://cloud.githubusercontent.com/assets/7847056/10753068/717c635a-7cb4-11e5-979c-6bd55c7fdd73.png)

Pls let me know if i have done anything wrong. I have already spend more thn 5 hrs on it.

**Comment by mgreter** [comment]
The binary is built in `bin` subfolder. I don't see any errors in your screenshots. Btw. we prefer actual pasted text, since it makes it searchable and copy-pasteable.

**Comment by techhysahil** [comment]
Here is detail text: 

Sahils-MacBook-Air:styleresearch sahil$ git clone https://github.com/sass/libsass.git
Cloning into 'libsass'...
remote: Counting objects: 13190, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 13190 (delta 9), reused 0 (delta 0), pack-reused 13166
Receiving objects: 100% (13190/13190), 8.47 MiB | 184.00 KiB/s, done.
Resolving deltas: 100% (7677/7677), done.
Checking connectivity... done.
Sahils-MacBook-Air:styleresearch sahil$ echo SASS_LIBSASS_PATH
SASS_LIBSASS_PATH
Sahils-MacBook-Air:styleresearch sahil$ echo $SASS_LIBSASS_PATH
”/Users/sahil/styleresearch/libsass”
Sahils-MacBook-Air:styleresearch sahil$ git clone https://github.com/sass/sassc.git
Cloning into 'sassc'...
remote: Counting objects: 3462, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 3462 (delta 3), reused 0 (delta 0), pack-reused 3453
Receiving objects: 100% (3462/3462), 1.51 MiB | 119.00 KiB/s, done.
Resolving deltas: 100% (1151/1151), done.
Checking connectivity... done.
Sahils-MacBook-Air:styleresearch sahil$ ls
libsass	sassc
Sahils-MacBook-Air:styleresearch sahil$ cd ./sassc
Sahils-MacBook-Air:sassc sahil$ make
/Library/Developer/CommandLineTools/usr/bin/make BUILD="static" -C ”/Users/sahil/styleresearch/libsass”
make: *** ”/Users/sahil/styleresearch/libsass”: No such file or directory.  Stop.
make: *** [libsass-static] Error 2
Sahils-MacBook-Air:sassc sahil$ open ~/.bash_profile
Sahils-MacBook-Air:sassc sahil$ echo $SASS_LIBSASS_PATH
”/Users/sahil/styleresearch/libsass”
Sahils-MacBook-Air:sassc sahil$ make
/Library/Developer/CommandLineTools/usr/bin/make BUILD="static" -C ”/Users/sahil/styleresearch/libsass”
make: *** ”/Users/sahil/styleresearch/libsass”: No such file or directory.  Stop.
make: *** [libsass-static] Error 2
Sahils-MacBook-Air:sassc sahil$ open ~/.bash_profile
Sahils-MacBook-Air:sassc sahil$ echo $SASS_LIBSASS_PATH
”/Users/sahil/styleresearch/libsass”
Sahils-MacBook-Air:sassc sahil$ source ~/.bash_profile
Sahils-MacBook-Air:sassc sahil$ echo $SASS_LIBSASS_PATH
/Users/sahil/styleresearch/libsass
Sahils-MacBook-Air:sassc sahil$ make
/Library/Developer/CommandLineTools/usr/bin/make BUILD="static" -C /Users/sahil/styleresearch/libsass
mkdir lib
cc -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/cencode.o src/cencode.c
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/ast.o src/ast.cpp
In file included from src/ast.cpp:1:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
src/ast.cpp:294:21: warning: expression with side effects will be evaluated despite being used as an operand to
      'typeid' [-Wpotentially-evaluated-expression]
        if ((typeid(*(*rhs)[i]) == typeid(Pseudo_Selector) || typeid(*(*rhs)[i]) == typeid(Wrapped_Sele...
                    ^
src/ast.cpp:294:70: warning: expression with side effects will be evaluated despite being used as an operand to
      'typeid' [-Wpotentially-evaluated-expression]
        if ((typeid(*(*rhs)[i]) == typeid(Pseudo_Selector) || typeid(*(*rhs)[i]) == typeid(Wrapped_Sele...
                                                                     ^
src/ast.cpp:302:20: warning: expression with side effects will be evaluated despite being used as an operand to
      'typeid' [-Wpotentially-evaluated-expression]
        if (typeid(*(*rhs)[i]) == typeid(Pseudo_Selector) || typeid(*(*rhs)[i]) == typeid(Wrapped_Selector))
                   ^
src/ast.cpp:302:69: warning: expression with side effects will be evaluated despite being used as an operand to
      'typeid' [-Wpotentially-evaluated-expression]
        if (typeid(*(*rhs)[i]) == typeid(Pseudo_Selector) || typeid(*(*rhs)[i]) == typeid(Wrapped_Selector))
                                                                    ^
6 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/base64vlq.o src/base64vlq.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/bind.o src/bind.cpp
In file included from src/bind.cpp:2:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/color_maps.o src/color_maps.cpp
In file included from src/color_maps.cpp:1:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/constants.o src/constants.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/context.o src/context.cpp
In file included from src/context.cpp:14:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/cssize.o src/cssize.cpp
In file included from src/cssize.cpp:5:
In file included from src/cssize.hpp:4:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/emitter.o src/emitter.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/environment.o src/environment.cpp
In file included from src/environment.cpp:1:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/error_handling.o src/error_handling.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/eval.o src/eval.cpp
In file included from src/eval.cpp:9:
In file included from src/eval.hpp:5:
In file included from src/listize.hpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
src/eval.cpp:584:70: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (operand->concrete_type() == Expression::NULL_VAL && typeid(*(u->operand())) == typeid(Variable)) {
                                                                     ^
3 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/expand.o src/expand.cpp
In file included from src/expand.cpp:8:
In file included from src/expand.hpp:6:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/extend.o src/extend.cpp
In file included from src/extend.cpp:5:
In file included from src/extend.hpp:6:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/file.o src/file.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/functions.o src/functions.cpp
In file included from src/functions.cpp:2:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/inspect.o src/inspect.cpp
In file included from src/inspect.cpp:8:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/json.o src/json.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/lexer.o src/lexer.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/listize.o src/listize.cpp
In file included from src/listize.cpp:5:
In file included from src/listize.hpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/memory_manager.o src/memory_manager.cpp
In file included from src/memory_manager.cpp:1:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/node.o src/node.cpp
In file included from src/node.cpp:3:
In file included from src/node.hpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/output.o src/output.cpp
In file included from src/output.cpp:1:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/parser.o src/parser.cpp
In file included from src/parser.cpp:4:
In file included from src/parser.hpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/plugins.o src/plugins.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/position.o src/position.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/prelexer.o src/prelexer.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/remove_placeholders.o src/remove_placeholders.cpp
In file included from src/remove_placeholders.cpp:1:
In file included from src/remove_placeholders.hpp:6:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass.o src/sass.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass_util.o src/sass_util.cpp
In file included from src/sass_util.cpp:1:
In file included from src/node.hpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass_values.o src/sass_values.cpp
In file included from src/sass_values.cpp:4:
In file included from src/eval.hpp:5:
In file included from src/listize.hpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass_context.o src/sass_context.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass_functions.o src/sass_functions.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass_interface.o src/sass_interface.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/sass2scss.o src/sass2scss.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/source_map.o src/source_map.cpp
In file included from src/source_map.cpp:7:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/to_c.o src/to_c.cpp
In file included from src/to_c.cpp:2:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/to_string.o src/to_string.cpp
In file included from src/to_string.cpp:6:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/to_value.o src/to_value.cpp
In file included from src/to_value.cpp:1:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/units.o src/units.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/utf8_string.o src/utf8_string.cpp
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/values.o src/values.cpp
In file included from src/values.cpp:2:
In file included from src/values.hpp:4:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
c++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.0-10-g77c9\"" -std=c++0x -I /Users/sahil/styleresearch/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/util.o src/util.cpp
In file included from src/util.cpp:2:
src/ast.hpp:2059:18: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
      if (typeid(*(*this)[0]) == typeid(Type_Selector))
                 ^
src/ast.hpp:2078:21: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
             typeid(*(*this)[0]) == typeid(Parent_Selector);
                    ^
2 warnings generated.
ar rcvs lib/libsass.a src/cencode.o src/ast.o src/base64vlq.o src/bind.o src/color_maps.o src/constants.o src/context.o src/cssize.o src/emitter.o src/environment.o src/error_handling.o src/eval.o src/expand.o src/extend.o src/file.o src/functions.o src/inspect.o src/json.o src/lexer.o src/listize.o src/memory_manager.o src/node.o src/output.o src/parser.o src/plugins.o src/position.o src/prelexer.o src/remove_placeholders.o src/sass.o src/sass_util.o src/sass_values.o src/sass_context.o src/sass_functions.o src/sass_interface.o src/sass2scss.o src/source_map.o src/to_c.o src/to_string.o src/to_value.o src/units.o src/utf8_string.o src/values.o src/util.o
a - src/cencode.o
a - src/ast.o
a - src/base64vlq.o
a - src/bind.o
a - src/color_maps.o
a - src/constants.o
a - src/context.o
a - src/cssize.o
a - src/emitter.o
a - src/environment.o
a - src/error_handling.o
a - src/eval.o
a - src/expand.o
a - src/extend.o
a - src/file.o
a - src/functions.o
a - src/inspect.o
a - src/json.o
a - src/lexer.o
a - src/listize.o
a - src/memory_manager.o
a - src/node.o
a - src/output.o
a - src/parser.o
a - src/plugins.o
a - src/position.o
a - src/prelexer.o
a - src/remove_placeholders.o
a - src/sass.o
a - src/sass_util.o
a - src/sass_values.o
a - src/sass_context.o
a - src/sass_functions.o
a - src/sass_interface.o
a - src/sass2scss.o
a - src/source_map.o
a - src/to_c.o
a - src/to_string.o
a - src/to_value.o
a - src/units.o
a - src/utf8_string.o
a - src/values.o
a - src/util.o
cc -Wall -O2 -DSASSC_VERSION="\"3.3.0\"" -I /Users/sahil/styleresearch/libsass/include -I /Users/sahil/styleresearch/libsass -stdlib=libc++ -fPIC -c -o sassc.o sassc.c
cc -Wall -O2 -Wl,-undefined,error -std=c++0x -stdlib=libc++ -ldl -fPIC -o bin/sassc sassc.o /Users/sahil/styleresearch/libsass/lib/libsass.a -lm -lstdc++ -ldl
Sahils-MacBook-Air:sassc sahil$ sassc
-bash: sassc: command not found

**Comment by mgreter** [comment]
As I said, binary is built in `bin` subfolder.
```
./bin/sassc
```

You cannot execute local binaries by just typing their name (at least on unix), so your command should more correctly be `./sassc`, but the binary is built in `bin`, so try `./bin/sassc`. HTH

**Comment by techhysahil** [comment]
Thanks Marcel Greter, now i am finally able to compile scss files. Still i have some queries, it would be great if you could help me with these.

1. After running it locally using ./bin/sassc now i have gloabal access to scss command which is doing same i suppose. How that happened? Actually i want to run it globally but before i do it somehow it's already working but i want to know how that happen or i am looking on something wrong.

2. In Compass i had config.rb file in which i used to write all the configurations and finally just run commands like compass compile/compass watch, Is there any such thing i can do here.
i checked sass-spec repo. sass_spec.rb file is alternative to config.rb i thought , but how to work with this. Is there any documentation/tutorial available.

3. --watch is not working for me, it's merely working as --update.

**Comment by mgreter** [comment]
Closing this as inactive as initial issue was solved.
