### ISSUE TITLE
El Capitan Brew is stuck at v3.2.5

### ISSUE THREAD

**Issue by aarongeorge** [sass/sassc#153]
Running `brew install sassc` is installing Sass at v3.2.5 instead of the current v3.3.2 on El Capitan.

It installs fine but it just seems like the latest version is not in the formula.

**Comment by xzyfer** [comment]
Firstly please only ask once. We get a lot of GitHub emails so you spamming
multiple issues just slows us down.

The homebrew packages are managed independently of us. Feel free to PR
homebrew to use the latest version of sassc. I have done this a couple
times before so you should be able to search for my previous PRs to learn
how.
