### ISSUE TITLE
Using variables containing "\" in value breaks soucemap

### ISSUE THREAD

**Issue by MelonHTML5** [sass/sassc#155]
When I include the fontAwesome scss files, the soucemap compiled by sassc will completely screw up. After some debugging, it turns our that using a variable containing \ is the cause.

```
// _variables.scss
$fa-var-glass: "\f000";
```

This breaks

```
content: $fa-var-glass;
```

This works

```
content: "\f000";
```

**Comment by am11** [comment]
This belongs to libsass: https://github.com/sass/libsass/issues.
/cc @mgreter

**Comment by mgreter** [comment]
Closing as @am11 correctly stated, this belongs to libsass and has already been answered.
https://github.com/sass/libsass/issues?utf8=%E2%9C%93&q=is%3Aissue%20fontawesome
