### ISSUE TITLE
&:not(:last-of-type) compiles to weird label:not(:last-of-type, :last-of-type)

### ISSUE THREAD

**Issue by Senthe** [sass/sassc#162]
This simple code:
```
label, a
  &:not(:last-of-type)
    margin-right: 70px
```
somehow compiles to:
```
label:not(:last-of-type, :last-of-type), a:not(:last-of-type, :last-of-type) {
  margin-right: 70px;
}
```
which isn't even working CSS syntax. I don't know what could be the cause.

**Comment by sultantarimo** [comment]
label, 
a{
	&:not(:last-of-type){
		margin-right: 70px
	}
}

works. compiles to: label:not(:last-of-type),a:not(:last-of-type){margin-right:70px}

**Comment by mgreter** [comment]
This should be fixed by upstream libsass now and should be included in next libsass tagged version.
