### ISSUE TITLE
Getting error 2 while doing 'make' 

### ISSUE THREAD

**Issue by aatish-shinde** [sass/sassc#175]
[root@misnvbdevwb1 sassc]# pwd
/usr/local/lib/sassc

[root@misnvbdevwb1 sassc]# make
make BUILD="static" -C /usr/local/lib
make[1]: Entering directory `/usr/local/lib'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/usr/local/lib'
make: *** [libsass-static] Error 2

The Makefile is present in the dir.

I am using following gcc version

[root@misnvbdevwb1 sassc]# gcc --version
gcc (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)

**Comment by mgreter** [comment]
Libsass needs gcc 4.6+ as mentioned on the main page in the libsass github repo: https://github.com/sass/libsass. Although I would have expected a different message in that case ...

**Comment by gknapp** [comment]
Seeing the same issue after compling `libsass`, then `sassc` with GCC 5.4.0

```bash
➜  sassc git:(5909ba5) pwd
/usr/local/lib/sassc
➜  sassc git:(5909ba5) make         
make BUILD="static" -C /usr/local/lib
make[1]: Entering directory '/usr/local/lib'
make[1]: *** No targets specified and no makefile found. Stop.
make[1]: Leaving directory '/usr/local/lib'
Makefile:212: recipe for target 'libsass-static' failed
make: *** [libsass-static] Error 2
➜  sassc git:(5909ba5) gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by saper** [comment]
@gknapp did you bootstrap sassc properly as indicated in the documentation?

**Comment by gknapp** [comment]
I was following a blog, which has a comment linking to askubuntu.com and linked to the libsass build docs. Followed those official build docs instead, moving `sassc` and `sass-spec` into libsass dir, then compiled fine. I commented on the askubuntu.com question saying the above also.

https://askubuntu.com/questions/849057/how-to-install-libsass-on-ubuntu-16-04/893126#comment1488679_899808
