### ISSUE TITLE
Publish artifacts as release assets

### ISSUE THREAD

**Issue by am11** [sass/sassc#190]
From https://github.com/sass/sassc/pull/189#issuecomment-245464707

Need to add a separate configuration in AppVeyor to publish the build artifacts as release assets. Ditto what we have in node-sass repo.

Note that for Travis CI, this would probably require us to provide an Amazon S3 bucket account. Since GitHub also uses Amazon S3 for storing assets, we may able to configure it (implicitly?). But that would require some investigation.

**Comment by xzyfer** [comment]
We won't tackle Travis release artefacts for now. Windows requires many fewer combinations of artefacts. Linux is much more combinatorially complex.

**Comment by am11** [comment]
Fixed by #189 for Windows builds.
