### ISSUE TITLE
Linux build instruction my be incorrect

### ISSUE THREAD

**Issue by xzyfer** [sass/sassc#191]
This friendly comment popped up Twitter. Suggests there might be an issue with updated Linux build instructions. Do you think you can take a look @nschonni?

https://twitter.com/jfhbrook/status/776807851851251712

**Comment by mgreter** [comment]
Seems to work as expected:
```
mkdir -p /my/facny/libsass/
cd /my/facny/libsass/
git clone http://www.github.com/sass/libsass
mkdir -p /some/where/else/sassc/
cd /some/where/else/sassc/
git clone http://www.github.com/sass/sassc
make -j4 SASS_LIBSASS_PATH=/my/facny/libsass/libsass/ -C sassc
# rm -r /my /some
```

```
# ./sassc/bin/sassc --version
sassc: 3.3.6-24-geee6
libsass: 3.3.6-121-gba92
sass2scss: 1.0.6
sass: 3.4
```

**Comment by jfhbrook** [comment]
I went through the effort of making Dockerfiles that demonstrate all the failing behavior I've been seeing trying to get this to work. Like I said on twitter, only cloning sassc inside of libsass works, everything else tries to cd into directories that don't exist.

https://github.com/jfhbrook/sass-tests/blob/master/Makefile

**Comment by jfhbrook** [comment]
Note that the failures are slightly different with each one. The tarball is missing the bootstrap script. The one without SASS_LIBSASS_PATH tries to cd into a garbage directory in order to clone libsass. The one *with* SASS_LIBSASS_PATH tries to cd into a *different* garbage directory.

**Comment by nschonni** [comment]
Thanks for the extra info @jfhbrook, I think there is something wrong with the bootstrap script. If I can't get it working correctly, i'll rollback https://github.com/sass/sassc/commit/58d72d6ac27e6ccfaa4393f2fcdf870f796dc776 so we just list the manual cloning steps again

**Comment by xzyfer** [comment]
@nschonni not sure if this is related but I'm now seeing failures in LibSass with autotools - https://travis-ci.org/sass/libsass/jobs/161605544

**Comment by xzyfer** [comment]
I rebuilt LibSass master to which was previously passing, to rule out my PR. It also fails. https://travis-ci.org/sass/libsass/builds/159534512

**Comment by JulienPalard** [comment]
Problem happen with a fresh clone of sassc without libsass:
```
  export SASS_LIBSASS_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../libsass/ && pwd )"
```

Will fail for those not having a libsass directory near their fresh clone of sassc, as the "cd" will fail:

```
# bash -x ./script/bootstrap 
+ set -e
+++ dirname ./script/bootstrap
++ cd ./script/../
++ pwd
+ SCRIPTPATH=/usr/src/sassc
+ '[' x == x ']'
+++ dirname ./script/bootstrap
++ cd ./script/../../libsass/
./script/bootstrap: line 8: cd: ./script/../../libsass/: No such file or directory
+ export SASS_LIBSASS_PATH=
+ SASS_LIBSASS_PATH=
+ echo 'SASS_LIBSASS_PATH variable is missing missing, so using '
SASS_LIBSASS_PATH variable is missing missing, so using 
+ '[' '!' -d '' ']'
+ git clone https://github.com/sass/libsass.git ''
fatal: could not create work tree dir ''.: No such file or directory
```

Also the doc states that we need a clone of libsass OR libsass being installed, which contradicts the intruction "type script/boostrap to clone libsass".

**Comment by stilllife00** [comment]
Not sure if it can help but with the latest master I had to add to my bashrc file the following:

     export SASS_LIBSASS_PATH=~/libsass
     export SASS_LIBSASS_PATH=~/libsass
     export SASS_SASSC_PATH=~/sassc
     export SASS_SPEC_PATH=~/sass-spec

With this, the bootstrap script will find the path where to clone/install the dependencies

**Comment by saper** [comment]
@stilllife00 can you post shell output if you don't set these?

**Comment by pfohlj** [comment]
Since @stilllife00 hasn't posted his shell output I'll post mine seeing as his fix worked for me also:

`vagrant@vagrant-ubuntu-trusty-64:~/temporary/sassc$ script/bootstrap
script/bootstrap: line 8: cd: script/../../libsass/: No such file or directory
SASS_LIBSASS_PATH variable is missing missing, so using
fatal: could not create work tree dir ''.: No such file or directory`

Hope that helps!

**Comment by saper** [comment]
Can you guys try https://github.com/sass/sassc/pull/193 and see if this is better?
