### ISSUE TITLE
cannot use the sass syntax when using stdin

### ISSUE THREAD

**Issue by docteurklein** [sass/sassc#204]
Hi there!

Is there something I'm missing or is the sass syntax not supported when reading from stdin?

    cat theme.sass | sassc -s

throws 
```
Error: Invalid CSS after "": expected 1 selector or at-rule, was "body"
        on line 1 of stdin
>>
   ^
```

with theme.sass containing:

    body
        color: #f00

The same with using the file input works tho:

``` 
% sassc theme.sass
body {
  color: #f00; }
```

Any idea?

**Comment by xzyfer** [comment]
I had a quick look at the code and you appear to be correct. LibSass looks at the file extension to determine how to parse the Sass code. If there is not file extension, i.e. stdin, it defaults to scss style.

We should add a flag to opt into indented style. Ruby Sass does the reverse, it defaults to the indented style and has a `--scss` flag.

**Comment by docteurklein** [comment]
thanks for the confirmation!
I was giving a look at the source code and I think I found something, but I cannot manage to compile my sources! (I followed the guide tho). 
Anyway, here is my attempt: #205

**Comment by xzyfer** [comment]
Thanks @docteurklein
