### ISSUE TITLE
Relative path @import

### ISSUE THREAD

**Issue by agzam** [sass/sassc#209]
Apparently brew formula got updated and now `sassc` on my machine is broken, trying to fix this, can someone help, please?

I have following directory structure:

    project
    └── src
    |   └── sass
    |       └── main.scss
    └── target 
        └── node_modules
            └── font-awesome
            |   └── scss
            |       └── font-awesome.scss
            └── react-datepicker
                └── src
                    └── stylesheets
                        └── datepicker.scss

now, in main.scss I have:

    @import 'target/node_modules/font-awesome/scss/font-awesome';
    @import 'target/node_modules/react-datepicker/src/stylesheets/datepicker'

And it used to work. Now it doesn't. I've tried all different combinations of setting `-I` flag etc, but it still complaining
```
File to import not found or unreadable
```
_I know that node_modules is not in the root, but that's irreleavant_

**Comment by mgreter** [comment]
From http://sass-lang.com/documentation/file.SASS_CHANGELOG.html
> The current working directory will no longer be placed onto the Sass load path by default. If you need the current working directory to be available, set SASS_PATH=. in your shell’s environment.

Please try `-I .` (libsass does not support SASS_PATH env variable AFAIR).

**Comment by agzam** [comment]
@mgreter I think that did the trick. Thank you very much!
