### ISSUE TITLE
uninitialized constant Sass::Deprecation

### ISSUE THREAD

**Issue by plentz** [sass/sassc#212]
Started with sass `v3.4.25`

```
Bundler::GemRequireError:
  There was an error while trying to load the gem 'sassc-rails'.
  Gem Load Error is: uninitialized constant Sass::Deprecation
  Backtrace for gem load error is:
  /usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:5:in `<class:String>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:4:in `<module:Value>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:2:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `require_relative'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `require_relative'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
```

related https://github.com/sass/sass/issues/2338

**Comment by meowsus** [comment]
This seems to be a Sass issue: https://github.com/sass/sass/issues/2340

**Comment by edariedl** [comment]
@meowsus Actually it probably isn't, the sass update also broke our app and after little bit of research I found out the same thing as mentioned here https://github.com/sass/sass/issues/2338#issuecomment-313978852 (issue created by @plentz in sass repo)

sassc requires only specific files from sass gem and relies on the internal implementation which can change (and did change in the last release).

When I removed sassc gem from our Gemfile and updated sass to `v3.4.25` everything worked as expected when I returned sassc it was suddenly broken.

**Comment by meowsus** [comment]
@edariedl Thanks. Yeah, I was a bit quick to comment, but found the same thing after a bit of research. I'm digging through sass/sassc-rails right now to see if I can't get a PR together for them.

**Comment by mgreter** [comment]
Closing since it appears to be downstream issue and already resolved.
