### ISSUE TITLE
Option -M / --omit-map-comment not working

### ISSUE THREAD

**Issue by mmodler** [sass/sassc#213]
> $ sassc -v
> sassc: 3.4.5
> libsass: 3.4.6
> sass2scss: 1.1.0
> sass: 3.4

We recently noticed that our sassc stack started adding sourceMappingURL comments at the end of the generated css files. Example:

`/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIj [and so on...] */`

Then i tried using sassc with -M or --omit-map-comment option, but with no effect. Upgrading from libsass 3.4.3 to 3.4.6 also had no effect.

I'm not sure if this is a sassc or libsass issue?

**Comment by xzyfer** [comment]
Do you know what version of libsass or sassc you had previously that wasn't
creating the sourcemap url?

**Comment by intact** [comment]
sassc can not (yet) embed source map into .css file

**Comment by mgreter** [comment]
> We recently noticed that our sassc stack started adding sourceMappingURL comments at the end of the generated css files.

@intact is right and it is highly doubtful that your stack was/is using sassc, as it has never had/set `sass_option_set_source_map_embed` so far (unless you used some unofficial version) ...
