### ISSUE TITLE
Cannot combine custom property with function?

### ISSUE THREAD

**Issue by mehaase** [sass/sassc#248]
If a custom property uses a function as its value, then the function is not actually called:

```bash
> cat test.scss
p {
    background-color: lighten(red, 10%);
    --custom-property: lighten(red, 10%);
    color: var(--custom-property);
}
> sassc -t expanded test.scss
p {
  background-color: #ff3333;
  --custom-property: lighten(red, 10%);
  color: var(--custom-property);
}
```

The background color and the custom property should have the same value.

In sassc 3.4.5, it does what I expect:

```
> sassc -t expanded test.scss
p {
  background-color: #ff3333;
  --custom-property: #ff3333;
  color: var(--custom-property);
}
```

**Comment by am11** [comment]
Please use the explicit evaluation syntax:

```sass
p {
  background-color: #ff3333;
  --custom-property: #{lighten(red, 10%)};
  color: var(--custom-property);
}
```

CSS4's custom property accept all values. Therefore in Sass, the evaluation cannot be implicitly inferred from the usage.

**Comment by mehaase** [comment]
Thanks! I didn't realize that explicit evaluation could be applied to functions, but this makes sense. I've tried what you suggested and it works.
