### ISSUE TITLE
"Installing sassc 2.4.0 with native extensions" takes a long time

### ISSUE THREAD

**Issue by gregschmit** [sass/sassc#272]
I am working on a project which uses sassc; when we run tests, they take a very long time and it seems to hang on "Installing sassc 2.4.0 with native extensions". Is there a way to fix this?

**Comment by saper** [comment]
Can you elaborate a bit what platform is this and how exactly sassc gets installed? Would be great to get some logs as a text dump.

**Comment by gregschmit** [comment]
Yes, I've tried on various Linux distros, FreeBSD, and macOS. I was migrating from a Rails 4 app (using `ruby-sass`), and tests ran very quickly. When I switched to `sassc`, it took several minutes longer, and it confused me. I even tried installing the system `sassc` on the platforms that provided it, but `bundle install` still wanted to install the gem, and the native extensions seemed to slow things down a lot. I wonder if trying to install a platform-specific gem would help things out, but it still seems like it's a very long time to install a gem.

Here is me installing `sassc` on the latest ruby/buster docker container:

<pre>
gns@gns-mac1 ~ % docker run -it ruby:latest /bin/bash
root@4f4bf2280063:/# time gem install ffi
Building native extensions. This could take a while...
Successfully installed ffi-1.13.1
1 gem installed

<b>real	0m7.137s</b>
user	0m5.407s
sys	0m1.055s
root@4f4bf2280063:/# time gem install sassc --verbose
HEAD https://rubygems.org/api/v1/dependencies
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=sassc
200 OK
GET https://rubygems.org/quick/Marshal.4.8/sassc-2.4.0.gemspec.rz
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=ffi
200 OK
Downloading gem sassc-2.4.0.gem
GET https://rubygems.org/gems/sassc-2.4.0.gem
Fetching sassc-2.4.0.gem
200 OK
/usr/local/bundle/gems/sassc-2.4.0/.gitignore
/usr/local/bundle/gems/sassc-2.4.0/.gitmodules
/usr/local/bundle/gems/sassc-2.4.0/.travis.yml
/usr/local/bundle/gems/sassc-2.4.0/CHANGELOG.md
/usr/local/bundle/gems/sassc-2.4.0/CODE_OF_CONDUCT.md
/usr/local/bundle/gems/sassc-2.4.0/Gemfile
/usr/local/bundle/gems/sassc-2.4.0/LICENSE.txt
/usr/local/bundle/gems/sassc-2.4.0/README.md
/usr/local/bundle/gems/sassc-2.4.0/Rakefile
/usr/local/bundle/gems/sassc-2.4.0/ext/depend
/usr/local/bundle/gems/sassc-2.4.0/ext/extconf.rb
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/VERSION
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/contrib/plugin.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass/base.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass/context.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass/functions.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass/values.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass/version.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/include/sass2scss.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/MurmurHash2.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast2c.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast2c.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_def_macros.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_fwd_decl.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_fwd_decl.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_helpers.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_sel_cmp.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_sel_super.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_sel_unify.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_sel_weave.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_selectors.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_selectors.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_supports.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_supports.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_values.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ast_values.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/b64/cencode.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/b64/encode.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/backtrace.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/backtrace.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/base64vlq.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/base64vlq.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/bind.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/bind.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/c2ast.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/c2ast.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/c99func.c
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/cencode.c
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/check_nesting.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/check_nesting.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/color_maps.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/color_maps.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/constants.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/constants.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/context.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/context.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/cssize.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/cssize.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/dart_helpers.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/debug.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/debugger.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/emitter.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/emitter.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/environment.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/environment.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/error_handling.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/error_handling.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/eval.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/eval.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/eval_selectors.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/expand.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/expand.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/extender.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/extender.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/extension.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/extension.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/file.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/file.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_colors.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_colors.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_lists.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_lists.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_maps.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_maps.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_miscs.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_miscs.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_numbers.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_numbers.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_selectors.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_selectors.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_strings.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_strings.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_utils.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/fn_utils.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/inspect.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/inspect.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/json.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/json.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/kwd_arg_macros.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/lexer.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/lexer.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/listize.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/listize.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/mapping.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory/allocator.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory/allocator.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory/config.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory/memory_pool.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory/shared_ptr.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/memory/shared_ptr.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/operation.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/operators.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/operators.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/ordered_map.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/output.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/output.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/parser.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/parser.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/parser_selectors.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/permutate.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/plugins.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/plugins.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/position.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/position.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/prelexer.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/prelexer.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/remove_placeholders.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/remove_placeholders.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass2scss.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass_context.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass_context.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass_functions.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass_functions.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass_values.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/sass_values.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/settings.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/source.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/source.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/source_data.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/source_map.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/source_map.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/stylesheet.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/stylesheet.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/to_value.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/to_value.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/units.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/units.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/utf8.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/utf8/checked.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/utf8/core.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/utf8/unchecked.h
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/utf8_string.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/utf8_string.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/util.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/util.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/util_string.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/util_string.hpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/values.cpp
/usr/local/bundle/gems/sassc-2.4.0/ext/libsass/src/values.hpp
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/dependency.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/engine.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/error.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/functions_handler.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/import_handler.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/importer.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/native_functions_api.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/sass2scss_api.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/sass_input_style.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/sass_output_style.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/sass_value.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/native/string_list.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/sass_2_scss.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/functions.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value/bool.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value/color.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value/list.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value/map.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value/number.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value/string.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/base.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/bool.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/color.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/list.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/map.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/number.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/script/value_conversion/string.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/util.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/util/normalized_map.rb
/usr/local/bundle/gems/sassc-2.4.0/lib/sassc/version.rb
/usr/local/bundle/gems/sassc-2.4.0/sassc.gemspec
/usr/local/bundle/gems/sassc-2.4.0/test/custom_importer_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/engine_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/error_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/fixtures/paths.scss
/usr/local/bundle/gems/sassc-2.4.0/test/functions_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/native_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/output_style_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/sass_2_scss_test.rb
/usr/local/bundle/gems/sassc-2.4.0/test/test_helper.rb
Building native extensions. This could take a while...
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
["/usr/local/bin/ruby", "-I", "/usr/local/lib/ruby/2.7.0", "-r", "./siteconf20200712-167-n5du3e.rb", "extconf.rb"]
creating Makefile
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
"make \"DESTDIR=\" clean"

current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
"make \"DESTDIR=\""
</pre>

**This is where it took ~2 minutes.**

<pre>
compiling ./libsass/src/ast.cpp
compiling ./libsass/src/ast2c.cpp
compiling ./libsass/src/ast_fwd_decl.cpp
compiling ./libsass/src/ast_sel_cmp.cpp
compiling ./libsass/src/ast_sel_super.cpp
compiling ./libsass/src/ast_sel_unify.cpp
compiling ./libsass/src/ast_sel_weave.cpp
compiling ./libsass/src/ast_selectors.cpp
compiling ./libsass/src/ast_supports.cpp
compiling ./libsass/src/ast_values.cpp
compiling ./libsass/src/backtrace.cpp
compiling ./libsass/src/base64vlq.cpp
compiling ./libsass/src/bind.cpp
compiling ./libsass/src/c2ast.cpp
compiling ./libsass/src/c99func.c
compiling ./libsass/src/cencode.c
compiling ./libsass/src/check_nesting.cpp
compiling ./libsass/src/color_maps.cpp
compiling ./libsass/src/constants.cpp
compiling ./libsass/src/context.cpp
compiling ./libsass/src/cssize.cpp
compiling ./libsass/src/emitter.cpp
compiling ./libsass/src/environment.cpp
compiling ./libsass/src/error_handling.cpp
compiling ./libsass/src/eval.cpp
compiling ./libsass/src/eval_selectors.cpp
compiling ./libsass/src/expand.cpp
compiling ./libsass/src/extender.cpp
compiling ./libsass/src/extension.cpp
compiling ./libsass/src/file.cpp
compiling ./libsass/src/fn_colors.cpp
compiling ./libsass/src/fn_lists.cpp
compiling ./libsass/src/fn_maps.cpp
compiling ./libsass/src/fn_miscs.cpp
compiling ./libsass/src/fn_numbers.cpp
compiling ./libsass/src/fn_selectors.cpp
compiling ./libsass/src/fn_strings.cpp
compiling ./libsass/src/fn_utils.cpp
compiling ./libsass/src/inspect.cpp
compiling ./libsass/src/json.cpp
compiling ./libsass/src/lexer.cpp
compiling ./libsass/src/listize.cpp
compiling ./libsass/src/memory/allocator.cpp
compiling ./libsass/src/memory/shared_ptr.cpp
compiling ./libsass/src/operators.cpp
compiling ./libsass/src/output.cpp
compiling ./libsass/src/parser.cpp
compiling ./libsass/src/parser_selectors.cpp
compiling ./libsass/src/plugins.cpp
compiling ./libsass/src/position.cpp
compiling ./libsass/src/prelexer.cpp
compiling ./libsass/src/remove_placeholders.cpp
compiling ./libsass/src/sass.cpp
compiling ./libsass/src/sass2scss.cpp
compiling ./libsass/src/sass_context.cpp
compiling ./libsass/src/sass_functions.cpp
compiling ./libsass/src/sass_values.cpp
compiling ./libsass/src/source.cpp
compiling ./libsass/src/source_map.cpp
compiling ./libsass/src/stylesheet.cpp
compiling ./libsass/src/to_value.cpp
compiling ./libsass/src/units.cpp
compiling ./libsass/src/utf8_string.cpp
compiling ./libsass/src/util.cpp
compiling ./libsass/src/util_string.cpp
compiling ./libsass/src/values.cpp
linking shared-object sassc/libsass.so
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
"make \"DESTDIR=\" install"
/usr/bin/install -c -m 0755 libsass.so ./.gem.20200712-167-sm6aue/sassc
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r ./siteconf20200712-167-n5du3e.rb extconf.rb
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
make "DESTDIR=" clean
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
make "DESTDIR="
current directory: /usr/local/bundle/gems/sassc-2.4.0/ext
make "DESTDIR=" install
Successfully installed sassc-2.4.0
1 gem installed

<b>real	2m21.017s</b>
user	2m11.993s
sys	0m8.384s
</pre>

**Comment by gregschmit** [comment]
Omg, also I just realized that the ruby gem is at `sassc-ruby`. Sorry for bothering you guys.

**Comment by saper** [comment]
No problem... Good you are using FreeBSD - libsass is there in FreeBSD ports so that could possibly speed up things a bit (if used). Compiling few C++ files will take a while on most platforms - the best way is to build a binary once and then just deploy. Not sure if sassc-ruby can use a pre-installed package though.
