### ISSUE TITLE
Allow for more complex at-media query

### ISSUE THREAD

**Issue by imme-emosol** [sass/sassc#277]
For instance, using:
`@media (prefers-color-scheme: light) or (prefers-color-scheme: no-preference) {`
results in:
```
SassC::SyntaxError: Error: Invalid CSS after "...-scheme: light)": expected "{", was "or (prefers-color-s"
         on line X:Y of Z.css.scss
>> @media (prefers-color-scheme: light) or (prefers-color-scheme: no-preference
   -----------------------------------^
```

**Comment by mgreter** [comment]
There is no "or" operator in the css spec, so your css is invalid, please use a comma!
https://css-tricks.com/logic-in-media-queries/

**Comment by imme-emosol** [comment]
Well that's embarrassing..
Thanks and sorry :|
