### ISSUE TITLE
Make it more accessible to Windows users.

### ISSUE THREAD

**Issue by zoomorph** [sass/sassc#54]
I was unable to compile this using any version of MSVC. Finally got it to build using MingW. Took several hours to figure out. Please don't leave Windows users stranded with Ruby!

It would be great to have:
- Compilation instructions for Windows
- Some precompiled binaries available
- Better support for MSVC (if feasible)

**Comment by Ciantic** [comment]
I also think this should provide compiled binaries for Windows.

I do have VS 2015, but I still find it annoying I have to compile this.

**Comment by mgreter** [comment]
http://libsass.ocbnet.ch/installer/

**Comment by am11** [comment]
Thanks @mgreter! This is great :smile:

**Comment by xzyfer** [comment]
@mgreter probably worth adding that to the read me.
