### ISSUE TITLE
Glob as input and folder as output supported?

### ISSUE THREAD

**Issue by CrocoDillon** [sass/sassc#62]
Currently I’m using `gulp-sass` a bit like (simplified for readability):

``` javascript
gulp.src('./public/sass/**/*.scss')
  .pipe(sass())
  .pipe(gulp.dest('./public/css'));
```

However I want to get rid of some of my build process’ dependencies and use a shell script or Makefile instead.

I can’t figure out how to use a glob for input and a folder for output though. Is this even possible? What about `--watch` which is supported by Ruby Sass?

If not, I can (as a Linux beginner, help is much appreciated) probably figure something out with `find --exec` or similar, but before going there I wanted to make sure first.

**Comment by benseven** [comment]
+1

We were using the Ruby gem [Sass-globbing](https://github.com/chriseppstein/sass-globbing) for this but want to use libsass / sassc at deployment rather than needing Ruby on our production server.

**Comment by xzyfer** [comment]
There no plans to implement this in the near future. Pull requests are welcome.

**Comment by thedavidmeister** [comment]
This would be cool. Globbing is now part of Rails and not a separate gem.

**Comment by CrocoDillon** [comment]
I closed this since I don't know how to implement this and no-one else seemed to have stepped up 😁 To be honest I forgot about this issue because it wasn't a concern for me anymore.

**Comment by thedavidmeister** [comment]
yeah i just moved to garden (https://github.com/noprompt/garden) and used the native clojure namespace tools to "glob" what i needed
