### ISSUE TITLE
Compiling sassc

### ISSUE THREAD

**Issue by yasin-amadmia-mck** [sass/sassc#79]
Hi,

Tried compiling sassc 3.0.2 with 3.0.2 libsass but it fails. OS is RHEL 6.x and I tried using GCC Version gcc version 4.7.2 and gcc version 4.4.x

BUILD="static" make -C /usr/local/src/sassc/libsass
make[1]: Entering directory `/usr/local/src/sassc/libsass'
g++ -std=c++0x -Wall -fPIC -O2  -c -o ast.o ast.cpp
In file included from ast.cpp:1:
ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
ast.hpp:211: error: ‘class std::unordered_map<Sass::Expression*, Sass::Expression*, std::hash<Sass::Expression*>, std::equal_to<Sass::Expression*>, std::allocator<std::pair<Sass::Expression* const, Sass::Expression*> > >’ has no member named ‘reserve’
ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
ast.hpp:236: error: expected initializer before ‘:’ token
ast.hpp:239: error: expected primary-expression before ‘return’
ast.hpp:239: error: expected ‘;’ before ‘return’
ast.hpp:239: error: expected primary-expression before ‘return’
ast.hpp:239: error: expected ‘)’ before ‘return’
ast.hpp: In member function ‘virtual bool Sass::Map::operator==(Sass::Expression&) const’:
ast.hpp:719: error: expected initializer before ‘:’ token
ast.hpp:721: error: expected primary-expression before ‘return’
ast.hpp:721: error: expected ‘;’ before ‘return’
ast.hpp:721: error: expected primary-expression before ‘return’
ast.hpp:721: error: expected ‘)’ before ‘return’
ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
ast.hpp:733: error: expected initializer before ‘:’ token
ast.hpp:736: error: expected primary-expression before ‘return’
ast.hpp:736: error: expected ‘;’ before ‘return’
ast.hpp:736: error: expected primary-expression before ‘return’
ast.hpp:736: error: expected ‘)’ before ‘return’
ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
ast.hpp:920: error: expected initializer before ‘:’ token
ast.hpp:923: error: expected primary-expression before ‘return’
ast.hpp:923: error: expected ‘;’ before ‘return’
ast.hpp:923: error: expected primary-expression before ‘return’
ast.hpp:923: error: expected ‘)’ before ‘return’
In file included from ast.cpp:1:
ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
ast.hpp:1257: error: expected initializer before ‘:’ token
ast.hpp:1260: error: expected primary-expression before ‘return’
ast.hpp:1260: error: expected ‘;’ before ‘return’
ast.hpp:1260: error: expected primary-expression before ‘return’
ast.hpp:1260: error: expected ‘)’ before ‘return’
make[1]: *** [ast.o] Error 1
make[1]: Leaving directory`/usr/local/src/sassc/libsass'
make: **\* [libsass-static] Error 2

**Comment by chrisnicola** [comment]
Currently having same this issue with GCC 4.5.4 on EngineYard's stack.

```
gem install sassc -v '1.7.1'
Fetching: sassc-1.7.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing sassc:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby22 -rubygems /usr/lib64/ruby/gems/2.2.0/gems/rake-0.9.6/bin/rake RUBYARCHDIR=/home/deploy/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/sassc-1.7.1 RUBYLIBDIR=/home/deploy/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/sassc-1.7.1
cd libsass
make lib/libsass.so LDFLAGS="-Wall -O2"
mkdir lib
cc -Wall -O2 -fPIC -c -o cencode.o cencode.c
g++ -Wall -O2 -std=c++0x -fPIC -c -o ast.o ast.cpp
In file included from ast.cpp:1:0:
ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
ast.hpp:238:21: error: expected initializer before ‘:’ token
ast.hpp:242:27: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’ to ‘bool’
ast.hpp:243:7: error: expected primary-expression before ‘return’
ast.hpp:243:7: error: expected ‘)’ before ‘return’
ast.hpp: In member function ‘virtual bool Sass::Map::operator==(Sass::Expression&) const’:
ast.hpp:807:23: error: expected initializer before ‘:’ token
ast.hpp:809:9: error: expected primary-expression before ‘return’
ast.hpp:809:9: error: expected ‘;’ before ‘return’
ast.hpp:809:9: error: expected primary-expression before ‘return’
ast.hpp:809:9: error: expected ‘)’ before ‘return’
ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
ast.hpp:822:21: error: expected initializer before ‘:’ token
ast.hpp:825:7: error: expected primary-expression before ‘return’
ast.hpp:825:7: error: expected ‘;’ before ‘return’
ast.hpp:825:7: error: expected primary-expression before ‘return’
ast.hpp:825:7: error: expected ‘)’ before ‘return’
ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
ast.hpp:1087:26: error: expected initializer before ‘:’ token
ast.hpp:1090:7: error: expected primary-expression before ‘return’
ast.hpp:1090:7: error: expected ‘;’ before ‘return’
ast.hpp:1090:7: error: expected primary-expression before ‘return’
ast.hpp:1090:7: error: expected ‘)’ before ‘return’
In file included from ast.cpp:1:0:
ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
ast.hpp:1349:24: error: expected initializer before ‘:’ token
ast.hpp:1352:7: error: expected primary-expression before ‘return’
ast.hpp:1352:7: error: expected ‘;’ before ‘return’
ast.hpp:1352:7: error: expected primary-expression before ‘return’
ast.hpp:1352:7: error: expected ‘)’ before ‘return’
ast.cpp: In member function ‘void Sass::Number::normalize(const std::string&)’:
ast.cpp:757:19: error: expected initializer before ‘:’ token
ast.cpp:944:1: error: expected primary-expression at end of input
ast.cpp:944:1: error: expected ‘;’ at end of input
ast.cpp:944:1: error: expected primary-expression at end of input
ast.cpp:944:1: error: expected ‘)’ at end of input
ast.cpp:944:1: error: expected statement at end of input
ast.cpp:944:1: error: expected ‘}’ at end of input
ast.cpp: At global scope:
ast.cpp:944:1: error: expected ‘}’ at end of input
units.hpp:11:16: warning: ‘Sass::PI’ defined but not used
make: *** [ast.o] Error 1
rake aborted!
Command failed with status (2): [make lib/libsass.so LDFLAGS="-Wall -O2"...]
/data/homedirs/deploy/.gem/ruby/2.2.0/gems/sassc-1.7.1/lib/tasks/libsass.rb:20:in `block (2 levels) in <top (required)>'
/data/homedirs/deploy/.gem/ruby/2.2.0/gems/sassc-1.7.1/lib/tasks/libsass.rb:11:in `block (3 levels) in <top (required)>'
/data/homedirs/deploy/.gem/ruby/2.2.0/gems/sassc-1.7.1/lib/tasks/libsass.rb:10:in `block (2 levels) in <top (required)>'
Tasks: TOP => lib/libsass.so
(See full trace by running task with --trace)

rake failed, exit code 1

```

**Comment by saper** [comment]
sassc is a command-line interface to [libsass](https://github.com/sass/libsass/) and GCC 4.6+ is required to compile it. libsass uses few C++11 features that are not available in the older compilers.

**Comment by chrisnicola** [comment]
Good to know, I was trying to build on EngineYard which is unfortunately still stuck at GCC 4.5. Are there any docs that specify requirements for compiling? That would help.

**Comment by saper** [comment]
The libsass README I have linked to in the comment above ^^
