### ISSUE TITLE
Question: Installing on Windows

### ISSUE THREAD

**Issue by anik786** [sass/sassc#94]
Hi,

Noob question, but how do you install this thing on windows. I've done it peice of cake on Ubuntu. However when using the make command on windows I get the following error: 

```
BUILD="static" make -C C:\libsass-3.1.0
'BUILD' is not recognized as an internal or external command,
operable program or batch file.
make: *** [libsass-static] Error 1
```

Note: I have set the libsass environment variable already!

Thanks! I really need to use this tool urgently.

**Comment by mgreter** [comment]
https://github.com/sass/libsass/wiki/Building-on-Windows
