### ISSUE TITLE
Question: Best tool to use with sassc for browser reloads ?

### ISSUE THREAD

**Issue by IbnSaeed** [sass/sassc#95]
Hello

Do we have to use node packages such as gulp or grunt to get the livereload workflow to work with sassc or is there another method.

I want to avoid installed node on my system and just stick with libsass + sassc + some browser reload tool

**Comment by xzyfer** [comment]
If you're using node already I recommend using node-sass rather then sassc directly. 

Then you can used either livereload or browsersync in your asset pipeline.
